name: build
on:
  push:
    branches:
      - main
jobs:
  build_code:
    name: "Build app & test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          - distribution: 'adopt'
          - java-version: '17'

      - name: Build & Test
        run: mvn verify

      - name: Generate JaCoCo Badge
          uses: cicirello/jacoco-badge-generator@v2
          with:
            generate-branches-badge: true


