name: Build & Test -> Publish
on:
  workflow_dispatch:

  push:
    branches:
      - master
jobs:
  build:
    name: "Build app & test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build & Test
        run: mvn verify

  publish-jar:
    needs: build
    name: "Publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
